# Generated by Django 5.2.11 on 2026-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='state_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
