# Generated by Django 5.2.11 on 2026-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_blood_group_clientprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='province',
            field=models.CharField(blank=True, choices=[('Koshi', 'Koshi'), ('Madesh', 'Madesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpaschim', 'Sudurpaschim')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='state_no',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2),
        ),
    ]
