# Generated by Django 5.2.11 on 2026-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='EMSC', max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('magnitude', models.FloatField()),
                ('occurred_at', models.CharField(max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
